name: OSS Track
description: Open source software project data collection or metadata
labels: ["track:oss"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
    validations:
      required: true
  - type: input
    id: github_url
    attributes:
      label: GitHub URL
      placeholder: https://github.com/org/repo
    validations:
      required: false